"use client";
import { motion } from "framer-motion";
import { Button } from "@/components/ui";
import TopBar from "@/components/layout/TopBar";
import { fadeInUp, staggerContainer } from "@/lib/animations";

export default function Home() {
  return (
    <div className="min-h-screen bg-background text-text">
      <TopBar />
      <main className="mx-auto max-w-6xl px-4 py-16">
        <section className="grid items-center gap-8 md:grid-cols-2">
          <motion.div
            variants={staggerContainer()}
            initial="hidden"
            animate="show"
            className="space-y-6"
          >
            <motion.h1 variants={fadeInUp} className="text-4xl font-bold md:text-5xl">
              Meeting notes, distilled.
            </motion.h1>
            <motion.p variants={fadeInUp} className="max-w-prose text-subtext">
              AutoNotez records, transcribes, and summarizes your meetings. Get
              action items, decisions, and key takeaways—automatically.
            </motion.p>
            <motion.div variants={fadeInUp} className="flex items-center gap-3">
              <Button>Start recording</Button>
              <Button variant="outline">View a demo</Button>
            </motion.div>
            <motion.div variants={fadeInUp} className="flex items-center gap-6 text-xs text-subtext">
              <div>Secure by default</div>
              <div>Powered by your LLM</div>
              <div>Export to anything</div>
            </motion.div>
          </motion.div>
          <motion.div
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.3, ease: "easeOut" }}
            className="rounded-xl border border-border bg-surface p-6 shadow-subtle"
          >
            <div className="h-[260px] w-full rounded-lg bg-linear-to-br from-primary/20 via-secondary/10 to-accent/10" />
            <div className="mt-4 grid grid-cols-3 gap-3 text-center text-sm">
              <div className="rounded-md border border-border bg-background p-3">
                <div className="text-2xl font-bold">98%</div>
                <div className="text-subtext">Accuracy</div>
              </div>
              <div className="rounded-md border border-border bg-background p-3">
                <div className="text-2xl font-bold">2x</div>
                <div className="text-subtext">Faster notes</div>
              </div>
              <div className="rounded-md border border-border bg-background p-3">
                <div className="text-2xl font-bold">0</div>
                <div className="text-subtext">Setup needed</div>
              </div>
            </div>
          </motion.div>
        </section>

        <section id="features" className="mt-24">
          <h2 className="text-2xl font-semibold">Features</h2>
          <div className="mt-6 grid gap-4 md:grid-cols-3">
            {[
              { title: "Record", desc: "Capture audio from any device." },
              { title: "Transcribe", desc: "Accurate transcripts, fast." },
              { title: "Summarize", desc: "Action items and decisions autogenerated." },
            ].map((f) => (
              <div key={f.title} className="rounded-xl border border-border bg-surface p-4">
                <div className="text-sm font-semibold">{f.title}</div>
                <div className="mt-1 text-sm text-subtext">{f.desc}</div>
              </div>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
